words = {
    "beginner": [
        {"word": "apple", "translation": "olma", "example": "I eat an apple every day."},
        {"word": "book", "translation": "kitob", "example": "She is reading a book."},
        {"word": "cat", "translation": "mushuk", "example": "The cat is sleeping."},
        {"word": "dog", "translation": "it", "example": "My dog likes to run."},
        {"word": "water", "translation": "suv", "example": "Please give me some water."},
        {"word": "house", "translation": "uy", "example": "We live in a big house."},
        {"word": "sun", "translation": "quyosh", "example": "The sun is very bright today."},
        {"word": "school", "translation": "maktab", "example": "I go to school every morning."},
        {"word": "friend", "translation": "do'st", "example": "He is my best friend."},
        {"word": "food", "translation": "ovqat", "example": "This food is delicious."},
        {"word": "car", "translation": "mashina", "example": "My father has a red car."},
        {"word": "tree", "translation": "daraxt", "example": "There is a big tree in the garden."},
        {"word": "milk", "translation": "sut", "example": "Children drink milk every day."},
        {"word": "bread", "translation": "non", "example": "We buy fresh bread every morning."},
        {"word": "hand", "translation": "qo'l", "example": "Wash your hands before eating."},
        {"word": "eye", "translation": "ko'z", "example": "She has beautiful blue eyes."},
        {"word": "door", "translation": "eshik", "example": "Please close the door."},
        {"word": "chair", "translation": "stul", "example": "Sit on the chair, please."},
        {"word": "table", "translation": "stol", "example": "Put the book on the table."},
        {"word": "phone", "translation": "telefon", "example": "He forgot his phone at home."},
        {"word": "money", "translation": "pul", "example": "I don't have enough money."},
        {"word": "road", "translation": "yo'l", "example": "The road is very long."},
        {"word": "city", "translation": "shahar", "example": "Tashkent is a big city."},
        {"word": "river", "translation": "daryo", "example": "We swam in the river."},
        {"word": "flower", "translation": "gul", "example": "She gave me a beautiful flower."},
        {"word": "hat", "translation": "shapka", "example": "He wears a hat in winter."},
        {"word": "shirt", "translation": "ko'ylak", "example": "I bought a new shirt yesterday."},
        {"word": "window", "translation": "deraza", "example": "Open the window, please."},
        {"word": "pen", "translation": "qalam", "example": "Can I borrow your pen?"},
        {"word": "bag", "translation": "sumka", "example": "She carries a heavy bag."},
        {"word": "bed", "translation": "karavot", "example": "I sleep in a comfortable bed."},
        {"word": "bird", "translation": "qush", "example": "The bird is singing."},
        {"word": "boat", "translation": "qayiq", "example": "We rode a boat on the lake."},
        {"word": "boy", "translation": "o'g'il bola", "example": "The boy is playing outside."},
        {"word": "girl", "translation": "qiz bola", "example": "The girl is reading a book."},
        {"word": "baby", "translation": "chaqaloq", "example": "The baby is sleeping."},
        {"word": "man", "translation": "erkak", "example": "The man is tall."},
        {"word": "woman", "translation": "ayol", "example": "The woman is kind."},
        {"word": "child", "translation": "bola", "example": "Every child needs love."},
        {"word": "family", "translation": "oila", "example": "We are a happy family."},
        {"word": "mother", "translation": "ona", "example": "My mother cooks very well."},
        {"word": "father", "translation": "ota", "example": "My father works every day."},
        {"word": "sister", "translation": "singil/opa", "example": "My sister is younger than me."},
        {"word": "brother", "translation": "aka/uka", "example": "My brother is very tall."},
        {"word": "color", "translation": "rang", "example": "What is your favorite color?"},
        {"word": "red", "translation": "qizil", "example": "She wore a red dress."},
        {"word": "blue", "translation": "ko'k", "example": "The sky is blue."},
        {"word": "green", "translation": "yashil", "example": "Grass is green."},
        {"word": "white", "translation": "oq", "example": "Snow is white."},
        {"word": "black", "translation": "qora", "example": "He has a black car."},
        {"word": "big", "translation": "katta", "example": "This is a big room."},
        {"word": "small", "translation": "kichik", "example": "The dog is small and cute."},
        {"word": "hot", "translation": "issiq", "example": "The soup is hot."},
        {"word": "cold", "translation": "sovuq", "example": "The water is cold."},
        {"word": "good", "translation": "yaxshi", "example": "She is a good student."},
        {"word": "bad", "translation": "yomon", "example": "This is a bad idea."},
        {"word": "happy", "translation": "baxtli", "example": "I am very happy today."},
        {"word": "sad", "translation": "g'amgin", "example": "Why are you sad?"},
        {"word": "fast", "translation": "tez", "example": "He runs very fast."},
        {"word": "slow", "translation": "sekin", "example": "The turtle is slow."},
        {"word": "old", "translation": "keksa/eski", "example": "My grandfather is old."},
        {"word": "new", "translation": "yangi", "example": "I have a new phone."},
        {"word": "open", "translation": "ochmoq", "example": "Please open the door."},
        {"word": "close", "translation": "yopmoq", "example": "Close your eyes."},
        {"word": "eat", "translation": "yemoq", "example": "I eat rice every day."},
        {"word": "drink", "translation": "ichmoq", "example": "She drinks tea in the morning."},
        {"word": "sleep", "translation": "uxlamoq", "example": "I sleep eight hours a day."},
        {"word": "walk", "translation": "yurmoq", "example": "We walk to school."},
        {"word": "run", "translation": "yugurmoq", "example": "He runs every morning."},
        {"word": "read", "translation": "o'qimoq", "example": "I read books every night."},
        {"word": "write", "translation": "yozmoq", "example": "She writes in her diary."},
        {"word": "speak", "translation": "gapirmoq", "example": "He speaks English well."},
        {"word": "listen", "translation": "eshitmoq", "example": "Listen to the teacher."},
        {"word": "see", "translation": "ko'rmoq", "example": "Can you see the mountain?"},
        {"word": "love", "translation": "sevmoq", "example": "I love my family."},
        {"word": "help", "translation": "yordam bermoq", "example": "Can you help me?"},
        {"word": "buy", "translation": "sotib olmoq", "example": "I want to buy a new shirt."},
        {"word": "sell", "translation": "sotmoq", "example": "He sells vegetables."},
        {"word": "give", "translation": "bermoq", "example": "Give me your hand."},
        {"word": "take", "translation": "olmoq", "example": "Take your bag."},
        {"word": "work", "translation": "ishlash", "example": "I work in an office."},
        {"word": "play", "translation": "o'ynash", "example": "Children love to play."},
        {"word": "learn", "translation": "o'rganmoq", "example": "I want to learn English."},
        {"word": "cook", "translation": "pishirmoq", "example": "My mother cooks dinner."},
        {"word": "clean", "translation": "tozalamoq", "example": "Please clean the room."},
        {"word": "rain", "translation": "yomg'ir", "example": "It rains a lot in April."},
        {"word": "snow", "translation": "qor", "example": "Snow is falling outside."},
        {"word": "wind", "translation": "shamol", "example": "The wind is strong today."},
        {"word": "sky", "translation": "osmon", "example": "The sky is clear today."},
        {"word": "moon", "translation": "oy", "example": "The moon is beautiful at night."},
        {"word": "star", "translation": "yulduz", "example": "I can see many stars tonight."},
        {"word": "night", "translation": "tun", "example": "Good night, everyone."},
        {"word": "day", "translation": "kun", "example": "Have a great day!"},
        {"word": "morning", "translation": "ertalab", "example": "Good morning!"},
        {"word": "evening", "translation": "kechqurun", "example": "Good evening, sir."},
        {"word": "week", "translation": "hafta", "example": "I go to the gym twice a week."},
        {"word": "month", "translation": "oy (muddat)", "example": "January is the first month."},
        {"word": "year", "translation": "yil", "example": "Happy New Year!"},
        {"word": "time", "translation": "vaqt", "example": "What time is it?"},
        {"word": "number", "translation": "son/raqam", "example": "What is your phone number?"},
        {"word": "name", "translation": "ism", "example": "My name is Ali."},
        {"word": "word", "translation": "so'z", "example": "I learned a new word today."},
        {"word": "sentence", "translation": "gap", "example": "Write a sentence in English."},
        {"word": "question", "translation": "savol", "example": "Ask a question if you don't understand."},
        {"word": "answer", "translation": "javob", "example": "What is the correct answer?"},
        {"word": "teacher", "translation": "o'qituvchi", "example": "My teacher is very kind."},
        {"word": "student", "translation": "talaba/o'quvchi", "example": "She is a good student."},
        {"word": "class", "translation": "sinf/dars", "example": "The class starts at 8 AM."},
        {"word": "desk", "translation": "yozuv stoli", "example": "Put your homework on the desk."},
        {"word": "notebook", "translation": "daftar", "example": "I write notes in my notebook."},
        {"word": "pencil", "translation": "qo'rg'oshin qalam", "example": "Use a pencil to draw."},
        {"word": "eraser", "translation": "o'chirg'ich", "example": "Give me the eraser, please."},
        {"word": "ruler", "translation": "chizg'ich", "example": "Draw a line with a ruler."},
        {"word": "paper", "translation": "qog'oz", "example": "Write your name on the paper."},
        {"word": "cup", "translation": "piyola/stakan", "example": "Drink from the cup."},
        {"word": "plate", "translation": "tovoq", "example": "Put the food on the plate."},
        {"word": "spoon", "translation": "qoshiq", "example": "Use a spoon to eat soup."},
        {"word": "fork", "translation": "vilka", "example": "He eats with a fork."},
        {"word": "knife", "translation": "pichoq", "example": "Be careful with the knife."},
        {"word": "glass", "translation": "stakan", "example": "Fill the glass with water."},
        {"word": "box", "translation": "quti", "example": "Put it in the box."},
        {"word": "ball", "translation": "to'p", "example": "Kick the ball!"},
        {"word": "game", "translation": "o'yin", "example": "Let's play a game."},
        {"word": "music", "translation": "musiqa", "example": "I love listening to music."},
        {"word": "song", "translation": "qo'shiq", "example": "She sings a beautiful song."},
        {"word": "dance", "translation": "raqs", "example": "Can you dance?"},
        {"word": "picture", "translation": "rasm", "example": "Draw a picture of your family."},
        {"word": "photo", "translation": "surat", "example": "Take a photo of this place."},
        {"word": "animal", "translation": "hayvon", "example": "A lion is a wild animal."},
        {"word": "fish", "translation": "baliq", "example": "I like eating fish."},
        {"word": "horse", "translation": "ot", "example": "The horse is running."},
        {"word": "cow", "translation": "sigir", "example": "The cow gives us milk."},
        {"word": "sheep", "translation": "qo'y", "example": "Sheep eat grass."},
        {"word": "chicken", "translation": "tovuq", "example": "We eat chicken every week."},
        {"word": "egg", "translation": "tuxum", "example": "I eat two eggs for breakfast."},
        {"word": "rice", "translation": "guruch/palov", "example": "Rice is our main food."},
        {"word": "meat", "translation": "go'sht", "example": "I don't eat meat."},
        {"word": "sugar", "translation": "shakar", "example": "Add sugar to the tea."},
        {"word": "salt", "translation": "tuz", "example": "Add a little salt."},
        {"word": "oil", "translation": "yog'", "example": "Cook with oil."},
        {"word": "tea", "translation": "choy", "example": "Do you want some tea?"},
        {"word": "coffee", "translation": "qahva", "example": "I drink coffee every morning."},
        {"word": "juice", "translation": "sharbat", "example": "Orange juice is healthy."},
        {"word": "butter", "translation": "sariyog'", "example": "Spread butter on the bread."},
        {"word": "cheese", "translation": "pishloq", "example": "I like cheese pizza."},
        {"word": "fruit", "translation": "meva", "example": "Eat more fruit every day."},
        {"word": "banana", "translation": "banan", "example": "Monkeys eat bananas."},
        {"word": "orange", "translation": "apelsin", "example": "Oranges are full of vitamin C."},
        {"word": "grape", "translation": "uzum", "example": "Grapes are sweet."},
        {"word": "vegetable", "translation": "sabzavot", "example": "Eat more vegetables."},
        {"word": "tomato", "translation": "pomidor", "example": "I need two tomatoes for the salad."},
        {"word": "potato", "translation": "kartoshka", "example": "She fried the potatoes."},
        {"word": "onion", "translation": "piyoz", "example": "Onions make you cry."},
        {"word": "garlic", "translation": "sarimsoq", "example": "Add garlic to the dish."},
        {"word": "carrot", "translation": "sabzi", "example": "Rabbits love carrots."},
        {"word": "park", "translation": "bog'/park", "example": "Let's go to the park."},
        {"word": "shop", "translation": "do'kon", "example": "I go to the shop every day."},
        {"word": "hospital", "translation": "kasalxona", "example": "He is in the hospital."},
        {"word": "bank", "translation": "bank", "example": "I need to go to the bank."},
        {"word": "market", "translation": "bozor", "example": "Let's buy from the market."},
        {"word": "airport", "translation": "aeroport", "example": "We arrived at the airport."},
        {"word": "station", "translation": "vokzal", "example": "Wait for me at the station."},
        {"word": "office", "translation": "ofis/idora", "example": "She works in an office."},
        {"word": "hotel", "translation": "mehmonxona", "example": "We stayed in a hotel."},
        {"word": "restaurant", "translation": "restoran", "example": "Let's eat at a restaurant."},
        {"word": "bathroom", "translation": "hammom", "example": "The bathroom is clean."},
        {"word": "kitchen", "translation": "oshxona", "example": "She is cooking in the kitchen."},
        {"word": "bedroom", "translation": "yotoqxona", "example": "My bedroom is small."},
        {"word": "garden", "translation": "bog'", "example": "I water the garden every day."},
        {"word": "roof", "translation": "tom", "example": "The cat is on the roof."},
        {"word": "wall", "translation": "devor", "example": "Paint the wall white."},
        {"word": "floor", "translation": "pol", "example": "The floor is clean."},
        {"word": "ceiling", "translation": "shift", "example": "The ceiling is very high."},
        {"word": "key", "translation": "kalit", "example": "Don't lose your key."},
        {"word": "lock", "translation": "qulf", "example": "Lock the door before you leave."},
        {"word": "light", "translation": "chiroq/yorug'lik", "example": "Turn on the light."},
        {"word": "fire", "translation": "olov", "example": "Don't play with fire."},
        {"word": "smoke", "translation": "tutun", "example": "I can see smoke from here."},
        {"word": "river", "translation": "daryo", "example": "We swam in the river."},
        {"word": "lake", "translation": "ko'l", "example": "The lake is beautiful."},
        {"word": "mountain", "translation": "tog'", "example": "The mountain is very high."},
        {"word": "forest", "translation": "o'rmon", "example": "Tigers live in the forest."},
        {"word": "beach", "translation": "qirg'oq/plyaj", "example": "Let's go to the beach."},
        {"word": "island", "translation": "orol", "example": "They live on a small island."},
        {"word": "sand", "translation": "qum", "example": "Walk barefoot on the sand."},
        {"word": "rock", "translation": "tosh", "example": "The rock is very heavy."},
        {"word": "land", "translation": "yer", "example": "This is our land."},
        {"word": "country", "translation": "mamlakat", "example": "Which country are you from?"},
        {"word": "world", "translation": "dunyo", "example": "The world is beautiful."},
        {"word": "people", "translation": "odamlar", "example": "Many people live here."},
        {"word": "life", "translation": "hayot", "example": "Life is short, enjoy it."},
        {"word": "age", "translation": "yosh", "example": "How old are you?"},
        {"word": "face", "translation": "yuz", "example": "She has a pretty face."},
        {"word": "nose", "translation": "burun", "example": "He has a big nose."},
        {"word": "mouth", "translation": "og'iz", "example": "Open your mouth."},
        {"word": "ear", "translation": "quloq", "example": "She has small ears."},
        {"word": "hair", "translation": "soch", "example": "She has long black hair."},
        {"word": "tooth", "translation": "tish", "example": "Brush your teeth twice a day."},
        {"word": "leg", "translation": "oyoq", "example": "My leg hurts."},
        {"word": "foot", "translation": "oyoq (panja)", "example": "Put your foot here."},
        {"word": "arm", "translation": "qo'l (bilak)", "example": "She broke her arm."},
        {"word": "back", "translation": "orqa/bel", "example": "My back hurts."},
        {"word": "head", "translation": "bosh", "example": "I have a headache."},
        {"word": "heart", "translation": "yurak", "example": "Your heart beats fast."},
        {"word": "stomach", "translation": "qorin", "example": "My stomach is empty."},
        {"word": "shoulder", "translation": "yelka", "example": "She tapped my shoulder."},
        {"word": "knee", "translation": "tizza", "example": "My knee hurts after running."},
        {"word": "finger", "translation": "barmoq", "example": "I cut my finger."},
        {"word": "skin", "translation": "teri", "example": "She has soft skin."},
        {"word": "blood", "translation": "qon", "example": "His blood pressure is high."},
        {"word": "health", "translation": "salomatlik", "example": "Health is more important than money."},
        {"word": "medicine", "translation": "dori", "example": "Take this medicine twice a day."},
        {"word": "pain", "translation": "og'riq", "example": "I feel pain in my leg."},
        {"word": "doctor", "translation": "shifokor", "example": "The doctor is very kind."},
        {"word": "nurse", "translation": "hamshira", "example": "The nurse helped me."},
        {"word": "police", "translation": "politsiya", "example": "Call the police now!"},
        {"word": "fire fighter", "translation": "o't o'chiruvchi", "example": "The fire fighter saved the child."},
        {"word": "driver", "translation": "haydovchi", "example": "The driver is careful."},
        {"word": "farmer", "translation": "dehqon", "example": "The farmer works in the field."},
        {"word": "soldier", "translation": "askar", "example": "The soldier is brave."},
        {"word": "lawyer", "translation": "advokat", "example": "She is a famous lawyer."},
        {"word": "engineer", "translation": "muhandis", "example": "He is a software engineer."},
        {"word": "cook", "translation": "oshpaz", "example": "The cook made a delicious meal."},
        {"word": "singer", "translation": "qo'shiqchi", "example": "She is a famous singer."},
        {"word": "actor", "translation": "aktyor", "example": "He is a great actor."},
        {"word": "sport", "translation": "sport", "example": "I love doing sport."},
        {"word": "football", "translation": "futbol", "example": "Football is popular here."},
        {"word": "basketball", "translation": "basketbol", "example": "He plays basketball well."},
        {"word": "swimming", "translation": "suzish", "example": "Swimming is good for health."},
        {"word": "running", "translation": "yugurish", "example": "Running is my hobby."},
        {"word": "bicycle", "translation": "velosiped", "example": "I ride a bicycle to school."},
        {"word": "train", "translation": "poyezd", "example": "The train arrives at 9 AM."},
        {"word": "bus", "translation": "avtobus", "example": "Take the bus to the city."},
        {"word": "ticket", "translation": "chipta", "example": "Buy a ticket for the show."},
        {"word": "passport", "translation": "pasport", "example": "Don't forget your passport."},
        {"word": "letter", "translation": "xat", "example": "I received a letter today."},
        {"word": "message", "translation": "xabar", "example": "Send me a message."},
        {"word": "internet", "translation": "internet", "example": "The internet is fast here."},
        {"word": "computer", "translation": "kompyuter", "example": "I work on a computer."},
        {"word": "television", "translation": "televizor", "example": "Turn off the television."},
        {"word": "radio", "translation": "radio", "example": "I listen to the radio."},
        {"word": "news", "translation": "yangiliklar", "example": "Watch the news at 8 PM."},
        {"word": "magazine", "translation": "jurnal", "example": "I read a magazine."},
        {"word": "newspaper", "translation": "gazeta", "example": "He reads the newspaper."},
        {"word": "clock", "translation": "soat (devoriy)", "example": "The clock on the wall shows 3."},
        {"word": "watch", "translation": "soat (qo'l)", "example": "My watch stopped working."},
        {"word": "calendar", "translation": "taqvim", "example": "Check the calendar."},
        {"word": "gift", "translation": "sovg'a", "example": "She gave me a gift."},
        {"word": "birthday", "translation": "tug'ilgan kun", "example": "Happy birthday!"},
        {"word": "party", "translation": "ziyofat", "example": "We had a great party."},
        {"word": "wedding", "translation": "to'y", "example": "Their wedding was beautiful."},
        {"word": "holiday", "translation": "bayram/ta'til", "example": "We went on a holiday."},
        {"word": "travel", "translation": "sayohat", "example": "I love to travel."},
        {"word": "hotel", "translation": "mehmonxona", "example": "The hotel is comfortable."},
        {"word": "map", "translation": "xarita", "example": "Look at the map."},
        {"word": "address", "translation": "manzil", "example": "What is your address?"},
        {"word": "street", "translation": "ko'cha", "example": "We live on a quiet street."},
        {"word": "bridge", "translation": "ko'prik", "example": "Cross the bridge carefully."},
        {"word": "sign", "translation": "belgi", "example": "Follow the signs."},
        {"word": "price", "translation": "narx", "example": "What is the price of this?"},
        {"word": "store", "translation": "do'kon/magazin", "example": "Let's go to the store."},
        {"word": "sale", "translation": "sotuv/chegirma", "example": "There is a big sale today."},
        {"word": "free", "translation": "bepul/erkin", "example": "This is free."},
        {"word": "cheap", "translation": "arzon", "example": "This shirt is cheap."},
        {"word": "expensive", "translation": "qimmat", "example": "Gold is expensive."},
        {"word": "hard", "translation": "qiyin/qattiq", "example": "This is a hard question."},
        {"word": "easy", "translation": "oson", "example": "This exercise is easy."},
        {"word": "clean", "translation": "toza", "example": "Keep your room clean."},
        {"word": "dirty", "translation": "iflos", "example": "The floor is dirty."},
        {"word": "wet", "translation": "ho'l", "example": "My clothes are wet."},
        {"word": "dry", "translation": "quruq", "example": "Dry your hands with the towel."},
        {"word": "full", "translation": "to'la", "example": "I am full after eating."},
        {"word": "empty", "translation": "bo'sh", "example": "The bottle is empty."},
        {"word": "tall", "translation": "baland/uzun bo'yli", "example": "He is very tall."},
        {"word": "short", "translation": "past bo'yli/qisqa", "example": "She is short but strong."},
        {"word": "long", "translation": "uzun", "example": "The road is very long."},
        {"word": "wide", "translation": "keng", "example": "The river is very wide."},
        {"word": "narrow", "translation": "tor", "example": "The path is narrow."},
        {"word": "round", "translation": "dumaloq", "example": "The earth is round."},
        {"word": "square", "translation": "to'rtburchak", "example": "The box is square."},
        {"word": "left", "translation": "chap", "example": "Turn left at the corner."},
        {"word": "right", "translation": "o'ng", "example": "Turn right here."},
        {"word": "up", "translation": "yuqori", "example": "Look up at the sky."},
        {"word": "down", "translation": "pastga", "example": "Put it down."},
        {"word": "inside", "translation": "ichida", "example": "Come inside."},
        {"word": "outside", "translation": "tashqarida", "example": "It is cold outside."},
        {"word": "near", "translation": "yaqin", "example": "The school is near."},
        {"word": "far", "translation": "uzoq", "example": "The city is far."},
        {"word": "first", "translation": "birinchi", "example": "I am first in class."},
        {"word": "last", "translation": "oxirgi", "example": "This is the last question."},
        {"word": "always", "translation": "har doim", "example": "I always wash my hands."},
        {"word": "never", "translation": "hech qachon", "example": "I never lie."},
        {"word": "sometimes", "translation": "ba'zida", "example": "I sometimes go to the cinema."},
        {"word": "often", "translation": "tez-tez", "example": "I often read books."},
        {"word": "now", "translation": "hozir", "example": "Come here now!"},
        {"word": "later", "translation": "keyinroq", "example": "We will talk later."},
        {"word": "today", "translation": "bugun", "example": "What will you do today?"},
        {"word": "yesterday", "translation": "kecha", "example": "I met him yesterday."},
        {"word": "tomorrow", "translation": "ertaga", "example": "See you tomorrow."},
        {"word": "again", "translation": "yana", "example": "Say it again, please."},
        {"word": "together", "translation": "birgalikda", "example": "Let's do it together."},
        {"word": "alone", "translation": "yolg'iz", "example": "She lives alone."},
        {"word": "maybe", "translation": "balki/ehtimol", "example": "Maybe I will come."},
        {"word": "sure", "translation": "albatta/ishonchli", "example": "I am sure about this."},
        {"word": "please", "translation": "iltimos", "example": "Help me, please."},
        {"word": "thank you", "translation": "rahmat", "example": "Thank you for your help."},
        {"word": "sorry", "translation": "kechirasiz/uzr", "example": "Sorry, I was late."},
        {"word": "yes", "translation": "ha", "example": "Yes, I understand."},
        {"word": "no", "translation": "yo'q", "example": "No, thank you."},
        {"word": "hello", "translation": "salom", "example": "Hello, how are you?"},
        {"word": "goodbye", "translation": "xayr", "example": "Goodbye! See you soon."},
        {"word": "welcome", "translation": "xush kelibsiz", "example": "Welcome to our school."},
        {"word": "excuse me", "translation": "uzringiz bor", "example": "Excuse me, where is the exit?"},
    ],

    "intermediate": [
        {"word": "achieve", "translation": "erishmoq", "example": "She worked hard to achieve her goal."},
        {"word": "adventure", "translation": "sarguzasht", "example": "Travelling is a great adventure."},
        {"word": "challenge", "translation": "qiyinchilik/sinov", "example": "Learning English is a big challenge."},
        {"word": "communicate", "translation": "muloqot qilmoq", "example": "It is important to communicate clearly."},
        {"word": "confident", "translation": "ishonchli", "example": "She feels confident in her job."},
        {"word": "curious", "translation": "qiziquvchan", "example": "Children are naturally curious."},
        {"word": "decision", "translation": "qaror", "example": "He made an important decision."},
        {"word": "describe", "translation": "tasvirlamoq", "example": "Can you describe what happened?"},
        {"word": "education", "translation": "ta'lim", "example": "Education is the key to success."},
        {"word": "effort", "translation": "harakat/sa'y", "example": "Success requires a lot of effort."},
        {"word": "experience", "translation": "tajriba", "example": "She has five years of experience."},
        {"word": "explain", "translation": "tushuntirmoq", "example": "Please explain the rules to me."},
        {"word": "freedom", "translation": "erkinlik", "example": "Everyone deserves freedom."},
        {"word": "generous", "translation": "saxiy", "example": "He is a very generous person."},
        {"word": "grateful", "translation": "minnatdor", "example": "I am grateful for your help."},
        {"word": "imagination", "translation": "tasavvur", "example": "Children have a great imagination."},
        {"word": "improve", "translation": "yaxshilamoq", "example": "I want to improve my English."},
        {"word": "independent", "translation": "mustaqil", "example": "She is a very independent woman."},
        {"word": "knowledge", "translation": "bilim", "example": "Knowledge is power."},
        {"word": "leadership", "translation": "rahbarlik", "example": "Good leadership inspires others."},
        {"word": "opportunity", "translation": "imkoniyat", "example": "This is a great opportunity for you."},
        {"word": "patient", "translation": "sabr-toqatli", "example": "Be patient; it takes time to learn."},
        {"word": "pollution", "translation": "ifloslanish", "example": "Air pollution is a serious problem."},
        {"word": "prevent", "translation": "oldini olmoq", "example": "We should prevent forest fires."},
        {"word": "respect", "translation": "hurmat", "example": "Always respect your elders."},
        {"word": "responsible", "translation": "mas'uliyatli", "example": "Be responsible for your actions."},
        {"word": "solution", "translation": "yechim", "example": "We need to find a solution quickly."},
        {"word": "suggest", "translation": "taklif qilmoq", "example": "I suggest we leave early."},
        {"word": "tradition", "translation": "an'ana", "example": "This is an old family tradition."},
        {"word": "volunteer", "translation": "ko'ngilli", "example": "She volunteers at the local hospital."},
        {"word": "accept", "translation": "qabul qilmoq", "example": "Please accept my apology."},
        {"word": "accurate", "translation": "aniq/to'g'ri", "example": "Your answer is accurate."},
        {"word": "advise", "translation": "maslahat bermoq", "example": "I advise you to study more."},
        {"word": "afford", "translation": "imkoni bo'lmoq", "example": "I can't afford this car."},
        {"word": "agree", "translation": "rozilik bildirmoq", "example": "I agree with your opinion."},
        {"word": "allow", "translation": "ruxsat bermoq", "example": "They don't allow phones here."},
        {"word": "announce", "translation": "e'lon qilmoq", "example": "The winner was announced today."},
        {"word": "appear", "translation": "ko'rinmoq/paydo bo'lmoq", "example": "Stars appear at night."},
        {"word": "apply", "translation": "murojaat qilmoq/qo'llamoq", "example": "Apply for the job online."},
        {"word": "arrange", "translation": "tartiblamoq", "example": "She arranged the flowers."},
        {"word": "attract", "translation": "jalb qilmoq", "example": "Music attracts many people."},
        {"word": "aware", "translation": "xabardor", "example": "Are you aware of the problem?"},
        {"word": "behave", "translation": "o'zini tutmoq", "example": "Behave yourself in class."},
        {"word": "believe", "translation": "ishonmoq", "example": "I believe you can do it."},
        {"word": "benefit", "translation": "foyda/naf", "example": "Exercise has many benefits."},
        {"word": "blame", "translation": "ayb qilmoq", "example": "Don't blame others for your mistakes."},
        {"word": "borrow", "translation": "qarz olmoq/o'g'irlamoq", "example": "Can I borrow your pen?"},
        {"word": "brave", "translation": "jasur", "example": "He was brave in the fight."},
        {"word": "capable", "translation": "qodir/iqtidorli", "example": "She is capable of doing this."},
        {"word": "careful", "translation": "ehtiyotkor", "example": "Be careful on the road."},
        {"word": "certain", "translation": "aniq/ma'lum", "example": "I am certain about this."},
        {"word": "change", "translation": "o'zgartirish/o'zgarmoq", "example": "Change is necessary for growth."},
        {"word": "character", "translation": "xarakter/belgi", "example": "He has a strong character."},
        {"word": "choice", "translation": "tanlov", "example": "Make the right choice."},
        {"word": "collect", "translation": "yig'moq/to'plamoq", "example": "She collects stamps."},
        {"word": "compare", "translation": "solishtirmoq", "example": "Compare these two options."},
        {"word": "complete", "translation": "tugatmoq/to'liq", "example": "Complete your homework first."},
        {"word": "consider", "translation": "o'ylab ko'rmoq", "example": "Consider all the options."},
        {"word": "contain", "translation": "o'z ichiga olmoq", "example": "The box contains books."},
        {"word": "continue", "translation": "davom ettirmoq", "example": "Continue reading the book."},
        {"word": "control", "translation": "nazorat qilmoq", "example": "Control your emotions."},
        {"word": "conversation", "translation": "suhbat", "example": "We had a long conversation."},
        {"word": "create", "translation": "yaratmoq", "example": "She created a beautiful painting."},
        {"word": "culture", "translation": "madaniyat", "example": "Every culture is unique."},
        {"word": "depend", "translation": "bog'liq bo'lmoq", "example": "It depends on the weather."},
        {"word": "develop", "translation": "rivojlantirmoq", "example": "He developed a new app."},
        {"word": "difference", "translation": "farq", "example": "What is the difference?"},
        {"word": "difficult", "translation": "qiyin", "example": "This task is difficult."},
        {"word": "discover", "translation": "kashf etmoq", "example": "Scientists discover new things."},
        {"word": "discuss", "translation": "muhokama qilmoq", "example": "Let's discuss this topic."},
        {"word": "emotion", "translation": "his-tuyg'u", "example": "Show your emotions freely."},
        {"word": "encourage", "translation": "rag'batlantirmoq", "example": "Encourage your children."},
        {"word": "energy", "translation": "energiya/kuch", "example": "She has a lot of energy."},
        {"word": "enjoy", "translation": "zavqlanmoq/yoqmoq", "example": "I enjoy reading books."},
        {"word": "environment", "translation": "muhit/atrof-muhit", "example": "Protect the environment."},
        {"word": "equal", "translation": "teng", "example": "All people are equal."},
        {"word": "establish", "translation": "tashkil etmoq", "example": "He established a new company."},
        {"word": "event", "translation": "voqea/tadbir", "example": "The event was a success."},
        {"word": "expect", "translation": "kutmoq/umid qilmoq", "example": "I expect good results."},
        {"word": "express", "translation": "ifodalash/bildirmoq", "example": "Express your feelings."},
        {"word": "fail", "translation": "muvaffaqiyatsiz bo'lmoq", "example": "Don't be afraid to fail."},
        {"word": "famous", "translation": "mashhur", "example": "She is a famous singer."},
        {"word": "focus", "translation": "e'tibor qaratmoq", "example": "Focus on your studies."},
        {"word": "force", "translation": "kuch/majburlamoq", "example": "Don't force people."},
        {"word": "foreign", "translation": "xorijiy", "example": "She speaks a foreign language."},
        {"word": "formal", "translation": "rasmiy", "example": "Wear formal clothes to the meeting."},
        {"word": "future", "translation": "kelajak", "example": "Plan for the future."},
        {"word": "global", "translation": "global/jahon", "example": "Climate change is a global problem."},
        {"word": "goal", "translation": "maqsad", "example": "Set a clear goal."},
        {"word": "government", "translation": "hukumat", "example": "The government made a new law."},
        {"word": "grow", "translation": "o'sish/rivojlanmoq", "example": "Children grow fast."},
        {"word": "guide", "translation": "yo'llovchi/yo'naltirmoq", "example": "She guided us through the city."},
        {"word": "healthy", "translation": "sog'lom", "example": "Eat healthy food."},
        {"word": "helpful", "translation": "foydali/yordamchi", "example": "She is very helpful."},
        {"word": "honest", "translation": "halol/rostgo'y", "example": "Always be honest."},
        {"word": "identify", "translation": "aniqlash/tanish", "example": "Identify the main problem."},
        {"word": "important", "translation": "muhim", "example": "This is very important."},
        {"word": "include", "translation": "o'z ichiga olmoq/qo'shmoq", "example": "Include everyone in the plan."},
        {"word": "increase", "translation": "oshirmoq/ko'paytirmoq", "example": "Increase your speed."},
        {"word": "industry", "translation": "sanoat", "example": "The oil industry is growing."},
        {"word": "influence", "translation": "ta'sir/ta'sir qilmoq", "example": "Music influences mood."},
        {"word": "information", "translation": "ma'lumot", "example": "I need more information."},
        {"word": "interact", "translation": "muloqot qilmoq/ta'sirlashmoq", "example": "People interact online."},
        {"word": "interest", "translation": "qiziqish/manfaat", "example": "I have an interest in art."},
        {"word": "issue", "translation": "muammo/masala", "example": "There is a serious issue."},
        {"word": "join", "translation": "qo'shilmoq", "example": "Join our group."},
        {"word": "judge", "translation": "hukm chiqarmoq/baholamoq", "example": "Don't judge people quickly."},
        {"word": "lack", "translation": "etishmaslik", "example": "There is a lack of water."},
        {"word": "local", "translation": "mahalliy", "example": "Buy local products."},
        {"word": "manage", "translation": "boshqarmoq/uddasidan chiqmoq", "example": "He manages the team well."},
        {"word": "method", "translation": "usul/yo'l", "example": "Use a better method."},
        {"word": "modern", "translation": "zamonaviy", "example": "We live in a modern city."},
        {"word": "natural", "translation": "tabiiy", "example": "Honey is a natural sweetener."},
        {"word": "necessary", "translation": "zarur", "example": "Sleep is necessary for health."},
        {"word": "negative", "translation": "salbiy/manfiy", "example": "Avoid negative thoughts."},
        {"word": "nervous", "translation": "asabiy/xavotirli", "example": "I felt nervous before the exam."},
        {"word": "notice", "translation": "sezmoq/e'tibor bermoq", "example": "Did you notice anything unusual?"},
        {"word": "offer", "translation": "taklif etmoq/taqdim etmoq", "example": "He offered me a job."},
        {"word": "opinion", "translation": "fikr", "example": "What is your opinion?"},
        {"word": "organize", "translation": "tashkil qilmoq", "example": "Please organize the event."},
        {"word": "overcome", "translation": "engib o'tmoq", "example": "Overcome your fears."},
        {"word": "participate", "translation": "ishtirok etmoq", "example": "Participate in class discussions."},
        {"word": "partner", "translation": "hamkor/sherik", "example": "She is my business partner."},
        {"word": "positive", "translation": "ijobiy/musbat", "example": "Stay positive always."},
        {"word": "potential", "translation": "salohiyat/imkoniyat", "example": "You have great potential."},
        {"word": "practice", "translation": "mashq qilmoq/amaliyot", "example": "Practice makes perfect."},
        {"word": "prepare", "translation": "tayyorlamoq", "example": "Prepare for the exam."},
        {"word": "pressure", "translation": "bosim/tazyiq", "example": "Don't put too much pressure on yourself."},
        {"word": "problem", "translation": "muammo", "example": "Solve the problem step by step."},
        {"word": "progress", "translation": "taraqqiyot/ilgarilash", "example": "I see your progress."},
        {"word": "protect", "translation": "himoya qilmoq", "example": "Protect the environment."},
        {"word": "provide", "translation": "ta'minlamoq/bermoq", "example": "He provides for his family."},
        {"word": "publish", "translation": "nashr etmoq", "example": "She published a new book."},
        {"word": "purpose", "translation": "maqsad/niyat", "example": "What is the purpose of this?"},
        {"word": "quality", "translation": "sifat", "example": "Always choose quality over price."},
        {"word": "realize", "translation": "anglamoq/ro'yobga chiqarmoq", "example": "I realized my mistake."},
        {"word": "reason", "translation": "sabab", "example": "What is the reason for this?"},
        {"word": "reduce", "translation": "kamaytirmoq", "example": "Reduce waste at home."},
        {"word": "relationship", "translation": "munosabat/aloqa", "example": "Build good relationships."},
        {"word": "remember", "translation": "eslamoq/yodda saqlash", "example": "Remember to call me."},
        {"word": "report", "translation": "hisobot/xabar bermoq", "example": "Write a report on this topic."},
        {"word": "research", "translation": "tadqiqot/o'rganmoq", "example": "She does research on cancer."},
        {"word": "result", "translation": "natija", "example": "What are the results?"},
        {"word": "role", "translation": "rol/vazifa", "example": "Play your role well."},
        {"word": "rule", "translation": "qoida", "example": "Follow the rules."},
        {"word": "safe", "translation": "xavfsiz", "example": "Stay safe on the road."},
        {"word": "satisfy", "translation": "qoniqtirmoq", "example": "The results satisfied everyone."},
        {"word": "schedule", "translation": "jadval/reja", "example": "Follow your schedule."},
        {"word": "serious", "translation": "jiddiy", "example": "This is a serious problem."},
        {"word": "situation", "translation": "vaziyat", "example": "The situation is under control."},
        {"word": "skill", "translation": "ko'nikma/mahorat", "example": "Develop your English skills."},
        {"word": "society", "translation": "jamiyat", "example": "We live in a modern society."},
        {"word": "source", "translation": "manba", "example": "Use a reliable source."},
        {"word": "standard", "translation": "standart/me'yor", "example": "Set high standards."},
        {"word": "strategy", "translation": "strategiya/reja", "example": "We need a new strategy."},
        {"word": "strengthen", "translation": "mustahkamlash", "example": "Strengthen your vocabulary."},
        {"word": "success", "translation": "muvaffaqiyat", "example": "Hard work leads to success."},
        {"word": "support", "translation": "qo'llab-quvvatlamoq", "example": "Support your friends."},
        {"word": "system", "translation": "tizim", "example": "We need a better system."},
        {"word": "talent", "translation": "iste'dod", "example": "She has a natural talent."},
        {"word": "technology", "translation": "texnologiya", "example": "Technology changes our lives."},
        {"word": "trust", "translation": "ishonch", "example": "Trust is very important."},
        {"word": "unique", "translation": "noyob/o'ziga xos", "example": "Everyone is unique."},
        {"word": "useful", "translation": "foydali", "example": "This app is very useful."},
        {"word": "value", "translation": "qiymat/ahamiyat", "example": "Family has great value."},
        {"word": "variety", "translation": "xilma-xillik", "example": "There is a variety of food here."},
        {"word": "vision", "translation": "ko'rish/maqsad", "example": "She has a clear vision."},
        {"word": "willing", "translation": "tayyor/istaydigan", "example": "Are you willing to help?"},
        {"word": "wisdom", "translation": "donolik/hikmat", "example": "Wisdom comes with age."},
        {"word": "achieve", "translation": "erishmoq", "example": "Work hard to achieve your dreams."},
        {"word": "adjust", "translation": "moslashtirmoq", "example": "Adjust to the new environment."},
        {"word": "admire", "translation": "qoyil qolmoq", "example": "I admire her courage."},
        {"word": "analysis", "translation": "tahlil", "example": "Do a careful analysis."},
        {"word": "approach", "translation": "yondashuv/yaqinlashmoq", "example": "Try a different approach."},
        {"word": "attitude", "translation": "munosabat/yondashuv", "example": "Your attitude matters."},
        {"word": "authority", "translation": "hokimiyat/vakolat", "example": "Respect authority."},
        {"word": "barrier", "translation": "to'siq", "example": "Break down the barriers."},
        {"word": "campaign", "translation": "kampaniya", "example": "They launched a campaign."},
        {"word": "candidate", "translation": "nomzod", "example": "She is a strong candidate."},
        {"word": "capacity", "translation": "sig'im/imkoniyat", "example": "We are at full capacity."},
        {"word": "category", "translation": "toifa/kategoriya", "example": "Which category does it belong to?"},
        {"word": "cause", "translation": "sabab bo'lmoq/sabab", "example": "What caused the problem?"},
        {"word": "climate", "translation": "iqlim", "example": "The climate is changing."},
        {"word": "competitive", "translation": "raqobatli", "example": "The job market is competitive."},
        {"word": "concept", "translation": "tushuncha/konsept", "example": "It's a difficult concept."},
        {"word": "conflict", "translation": "mojarо/ziddiyat", "example": "Avoid conflict at work."},
        {"word": "connect", "translation": "bog'lamoq/ulashmoq", "example": "Connect with your friends."},
        {"word": "contribute", "translation": "hissa qo'shmoq", "example": "Contribute to the team."},
        {"word": "convince", "translation": "ishontirmoq", "example": "He convinced me to try."},
        {"word": "cope", "translation": "uddasidan chiqmoq/dosh bermoq", "example": "How do you cope with stress?"},
        {"word": "creative", "translation": "ijodiy", "example": "Be more creative."},
        {"word": "critical", "translation": "tanqidiy/muhim", "example": "Be critical of your work."},
        {"word": "deadline", "translation": "muddat/oxirgi kun", "example": "The deadline is tomorrow."},
        {"word": "demand", "translation": "talab qilmoq/talab", "example": "The demand for oil is rising."},
        {"word": "design", "translation": "dizayn/loyiha", "example": "The design is beautiful."},
        {"word": "detail", "translation": "tafsilot/detal", "example": "Pay attention to details."},
        {"word": "digital", "translation": "raqamli", "example": "We live in a digital world."},
        {"word": "discipline", "translation": "intizom/fan", "example": "Discipline is key to success."},
        {"word": "distance", "translation": "masofa", "example": "The distance is 10 km."},
        {"word": "diverse", "translation": "xilma-xil", "example": "Our team is very diverse."},
        {"word": "effective", "translation": "samarali", "example": "Find an effective solution."},
        {"word": "efficient", "translation": "samarali/unumli", "example": "Work in an efficient way."},
        {"word": "elaborate", "translation": "batafsil tushuntirmoq", "example": "Please elaborate on your idea."},
        {"word": "eliminate", "translation": "yo'q qilmoq", "example": "Eliminate distractions."},
        {"word": "emphasize", "translation": "ta'kidlamoq", "example": "The teacher emphasized the rules."},
        {"word": "engage", "translation": "jalb etmoq/band bo'lmoq", "example": "Engage with your audience."},
        {"word": "enhance", "translation": "yaxshilamoq/oshirmoq", "example": "Enhance your skills daily."},
        {"word": "essential", "translation": "zarur/muhim", "example": "Water is essential for life."},
        {"word": "evaluate", "translation": "baholamoq", "example": "Evaluate your performance."},
        {"word": "evolve", "translation": "rivojlanmoq/o'zgarmoq", "example": "Technology evolves rapidly."},
        {"word": "expand", "translation": "kengaytirmoq", "example": "Expand your knowledge."},
        {"word": "feature", "translation": "xususiyat/belgi", "example": "This phone has great features."},
        {"word": "flexible", "translation": "moslashuvchan", "example": "Be flexible with your plans."},
        {"word": "function", "translation": "vazifa/ishlash", "example": "What is the function of this button?"},
        {"word": "fundamental", "translation": "asosiy", "example": "Trust is fundamental."},
        {"word": "generate", "translation": "hosil qilmoq/ishlab chiqarmoq", "example": "Generate new ideas."},
        {"word": "hypothesis", "translation": "faraz/gipoteza", "example": "Test your hypothesis."},
        {"word": "impact", "translation": "ta'sir/zarba", "example": "Technology has a big impact."},
        {"word": "implement", "translation": "amalga oshirmoq", "example": "Implement the new plan."},
        {"word": "initiative", "translation": "tashabbuskorlik", "example": "Take the initiative."},
        {"word": "innovation", "translation": "innovatsiya/yangilik", "example": "Innovation drives progress."},
        {"word": "inspire", "translation": "ilhomlantiranmoq", "example": "She inspired many people."},
        {"word": "interpret", "translation": "talqin qilmoq", "example": "Interpret the data correctly."},
        {"word": "investment", "translation": "investitsiya/sarmoya", "example": "Education is a good investment."},
        {"word": "involve", "translation": "jalb etmoq/o'z ichiga olmoq", "example": "Involve everyone in the process."},
        {"word": "justify", "translation": "asoslash/oqlash", "example": "Justify your decision."},
        {"word": "maintain", "translation": "saqlamoq/qo'llab-quvvatlamoq", "example": "Maintain a healthy lifestyle."},
        {"word": "maximize", "translation": "maksimallashtirmoq", "example": "Maximize your efficiency."},
        {"word": "measure", "translation": "o'lchash/baholash", "example": "Measure your progress weekly."},
        {"word": "mentor", "translation": "murabbiy/usoz", "example": "Find a good mentor."},
        {"word": "motivate", "translation": "rag'batlantirmoq", "example": "Motivate yourself every day."},
        {"word": "negotiate", "translation": "muzokarа olib bormoq", "example": "Learn to negotiate."},
        {"word": "objective", "translation": "maqsad/ob'ektiv", "example": "Set clear objectives."},
        {"word": "observe", "translation": "kuzatmoq", "example": "Observe the situation carefully."},
        {"word": "obtain", "translation": "olmoq/qo'lga kiritmoq", "example": "Obtain the necessary documents."},
        {"word": "outcome", "translation": "natija/oqibat", "example": "The outcome was positive."},
        {"word": "outline", "translation": "reja/sxema", "example": "Outline your main points."},
        {"word": "pattern", "translation": "naqsh/andoza", "example": "Notice the pattern."},
        {"word": "perform", "translation": "ijro etmoq/bajarmoq", "example": "Perform your best."},
        {"word": "persist", "translation": "qat'iyatli bo'lmoq/davom etmoq", "example": "Persist despite difficulties."},
        {"word": "perspective", "translation": "nuqtai nazar", "example": "See it from a new perspective."},
        {"word": "phase", "translation": "bosqich/faza", "example": "We are in the first phase."},
        {"word": "precise", "translation": "aniq", "example": "Be precise in your calculations."},
        {"word": "principle", "translation": "tamoyil/asos", "example": "Follow your principles."},
        {"word": "priority", "translation": "ustuvorlik", "example": "Education is my priority."},
        {"word": "process", "translation": "jarayon", "example": "The process takes time."},
        {"word": "professional", "translation": "professional/mutaxassis", "example": "She is very professional."},
        {"word": "propose", "translation": "taklif qilmoq", "example": "He proposed a new plan."},
        {"word": "qualify", "translation": "layoqatli bo'lmoq", "example": "You qualify for the job."},
        {"word": "reflect", "translation": "aks ettirmoq/o'ylab ko'rmoq", "example": "Reflect on your mistakes."},
        {"word": "relevant", "translation": "tegishli/muhim", "example": "Is this information relevant?"},
        {"word": "reliable", "translation": "ishonchli", "example": "She is a reliable worker."},
        {"word": "require", "translation": "talab qilmoq/kerak bo'lmoq", "example": "This job requires experience."},
        {"word": "resource", "translation": "resurs/manba", "example": "Use your resources wisely."},
        {"word": "response", "translation": "javob/munosabat", "example": "Give a quick response."},
        {"word": "reveal", "translation": "ochib ko'rsatmoq/fosh qilmoq", "example": "The report revealed new facts."},
        {"word": "significant", "translation": "muhim/sezilarli", "example": "There is a significant change."},
        {"word": "specific", "translation": "aniq/muayyan", "example": "Be specific in your request."},
        {"word": "stable", "translation": "barqaror", "example": "We need a stable internet."},
        {"word": "stimulate", "translation": "rag'batlantirmoq/kuchaytirmoq", "example": "Coffee can stimulate the brain."},
        {"word": "stress", "translation": "stress/ta'kidlamoq", "example": "Manage your stress well."},
        {"word": "structure", "translation": "tuzilma/qurilma", "example": "The structure is clear."},
        {"word": "struggle", "translation": "kurash/qiynalmoq", "example": "Don't give up in the struggle."},
        {"word": "substantial", "translation": "muhim/katta", "example": "There is substantial evidence."},
        {"word": "sufficient", "translation": "yetarli", "example": "Is this sufficient for you?"},
        {"word": "summarize", "translation": "xulosa qilmoq", "example": "Summarize the main points."},
        {"word": "sustainable", "translation": "barqaror/uzoq muddatli", "example": "Use sustainable energy."},
        {"word": "target", "translation": "maqsad/nishon", "example": "We reached our target."},
        {"word": "transfer", "translation": "o'tkazmoq/ko'chirmoq", "example": "Transfer the money today."},
        {"word": "transform", "translation": "o'zgartirmoq/aylantirmoq", "example": "Transform your habits."},
        {"word": "trend", "translation": "tendentsiya/moda", "example": "This is a new trend."},
        {"word": "ultimate", "translation": "eng yuqori/yakuniy", "example": "This is the ultimate goal."},
        {"word": "underline", "translation": "ta'kidlamoq/chiziq tortmoq", "example": "Underline the key words."},
        {"word": "update", "translation": "yangilamoq", "example": "Update your software."},
        {"word": "valid", "translation": "haqiqiy/to'g'ri", "example": "Your argument is valid."},
        {"word": "verify", "translation": "tasdiqlash/tekshirish", "example": "Verify the information first."},
        {"word": "vital", "translation": "hayotiy/muhim", "example": "Water is vital for life."},
    ],

    "advanced": [
        {"word": "ambiguous", "translation": "noaniq/ikki ma'noli", "example": "His answer was ambiguous."},
        {"word": "anticipate", "translation": "oldindan kutmoq", "example": "We anticipate strong growth next year."},
        {"word": "articulate", "translation": "aniq ifodalash", "example": "She could articulate her ideas clearly."},
        {"word": "assertion", "translation": "da'vo/ta'kid", "example": "His assertion was supported by evidence."},
        {"word": "autonomous", "translation": "mustaqil/avtonom", "example": "The robot is fully autonomous."},
        {"word": "catalyst", "translation": "katalizator/turtki", "example": "Education can be a catalyst for change."},
        {"word": "coherent", "translation": "izchil/mantiqli", "example": "Please give a coherent explanation."},
        {"word": "collaborate", "translation": "hamkorlik qilmoq", "example": "Teams collaborate to solve complex problems."},
        {"word": "complexity", "translation": "murakkablik", "example": "The complexity of the issue surprised everyone."},
        {"word": "comprehensive", "translation": "keng qamrovli", "example": "She wrote a comprehensive report."},
        {"word": "consequence", "translation": "oqibat/natija", "example": "Think about the consequences."},
        {"word": "contradict", "translation": "qarama-qarshi bo'lmoq", "example": "His actions contradict his words."},
        {"word": "controversy", "translation": "munozara/bahs", "example": "The new law sparked controversy."},
        {"word": "deduce", "translation": "xulosa chiqarmoq", "example": "From the clues, we can deduce the answer."},
        {"word": "deteriorate", "translation": "yomonlashmoq", "example": "His health began to deteriorate."},
        {"word": "dilemma", "translation": "ikkilanish/qiyin tanlov", "example": "She faced a difficult dilemma."},
        {"word": "eloquent", "translation": "notiq/ta'sirchan", "example": "He gave an eloquent speech."},
        {"word": "ethical", "translation": "axloqiy", "example": "We must consider the ethical implications."},
        {"word": "innovative", "translation": "innovatsion", "example": "The company developed an innovative solution."},
        {"word": "meticulous", "translation": "puxta/diqqatli", "example": "She is meticulous in her research."},
        {"word": "notion", "translation": "tushuncha/g'oya", "example": "I have no notion of what he means."},
        {"word": "paradigm", "translation": "paradigma/namuna", "example": "This discovery shifted the scientific paradigm."},
        {"word": "phenomenon", "translation": "hodisa/fenomen", "example": "The northern lights are a natural phenomenon."},
        {"word": "scrutinize", "translation": "sinchiklab tekshirmoq", "example": "The committee will scrutinize the proposal."},
        {"word": "aberration", "translation": "chetga chiqish/og'ish", "example": "This behaviour is an aberration from the norm."},
        {"word": "abstain", "translation": "o'zini tutmoq/tiymoq", "example": "He abstained from voting."},
        {"word": "accrue", "translation": "to'planmoq/yig'ilmoq", "example": "Interest accrues monthly."},
        {"word": "acquiesce", "translation": "rozi bo'lmoq/tan olmoq", "example": "She acquiesced to the demands."},
        {"word": "admonish", "translation": "ogohlantiirmoq/tanbeh bermoq", "example": "The teacher admonished the student."},
        {"word": "advocate", "translation": "himoya qilmoq/tarafdor", "example": "She advocates for human rights."},
        {"word": "alleviate", "translation": "yengillashtirmoq", "example": "This medicine will alleviate the pain."},
        {"word": "allude", "translation": "ishorat qilmoq/bildirib o'tmoq", "example": "He alluded to the problem."},
        {"word": "ambivalent", "translation": "ikkilangan/qarama-qarshi his", "example": "I feel ambivalent about the offer."},
        {"word": "ameliorate", "translation": "yaxshilamoq", "example": "We must ameliorate the living conditions."},
        {"word": "anachronism", "translation": "zamonga to'g'ri kelmaslik", "example": "That idea is an anachronism."},
        {"word": "anecdote", "translation": "qisqa hikoya/voqea", "example": "He told a funny anecdote."},
        {"word": "annihilate", "translation": "yo'q qilmoq/mahv etmoq", "example": "The disease annihilated the crops."},
        {"word": "anomaly", "translation": "g'ayritabiiy holat/og'ish", "example": "This result is an anomaly."},
        {"word": "antagonize", "translation": "dushman qilmoq", "example": "Don't antagonize your coworkers."},
        {"word": "apathy", "translation": "befarqlik/loqaydlik", "example": "Voter apathy is a serious concern."},
        {"word": "apprehend", "translation": "ushlamoq/tushunmoq", "example": "The police apprehended the suspect."},
        {"word": "arduous", "translation": "og'ir/charchatuvchi", "example": "It was an arduous journey."},
        {"word": "astute", "translation": "ziyrak/o'tkir zehni", "example": "She is an astute businesswoman."},
        {"word": "atrophy", "translation": "zaiflamoq/so'lmoq", "example": "Muscles atrophy without exercise."},
        {"word": "audacious", "translation": "jasur/dadil", "example": "It was an audacious plan."},
        {"word": "augment", "translation": "oshirmoq/kuchaytirmoq", "example": "Augment your income with a side job."},
        {"word": "aversion", "translation": "nafrat/antipiya", "example": "She has an aversion to loud noise."},
        {"word": "axiom", "translation": "aksioma/asosiy haqiqat", "example": "It is an axiom that honesty is best."},
        {"word": "belligerent", "translation": "jangari/tajovuzkor", "example": "The belligerent crowd caused trouble."},
        {"word": "benevolent", "translation": "mehr-shafqatli/saxiy", "example": "She is a benevolent leader."},
        {"word": "bewildering", "translation": "hayratlanarli/chalkashtiradigan", "example": "The instructions were bewildering."},
        {"word": "bifurcate", "translation": "ikki shohaga bo'linmoq", "example": "The road bifurcates here."},
        {"word": "bolster", "translation": "mustahkamlash/kuchaytirmoq", "example": "New data bolsters our argument."},
        {"word": "bombastic", "translation": "maqtanchoq/bo'rttirilgan", "example": "His speech was bombastic."},
        {"word": "brevity", "translation": "qisqalik", "example": "Brevity is the soul of wit."},
        {"word": "cacophony", "translation": "shovqin/qo'pol ovozlar", "example": "The city was full of cacophony."},
        {"word": "capitulate", "translation": "taslim bo'lmoq", "example": "He capitulated under pressure."},
        {"word": "capricious", "translation": "o'zgaruvchan/kayfiyatga qarab ish tutuvchi", "example": "The weather was capricious."},
        {"word": "castigate", "translation": "qattiq tanqid qilmoq", "example": "The report castigated the management."},
        {"word": "cataclysm", "translation": "falokat/katta halokatli voqea", "example": "The earthquake was a cataclysm."},
        {"word": "caustic", "translation": "o'tkir/kuydiradigan", "example": "Her caustic remarks hurt everyone."},
        {"word": "cerebral", "translation": "aqliy/fikrga asoslangan", "example": "Chess is a cerebral game."},
        {"word": "circumvent", "translation": "aylanib o'tmoq/chetlab o'tmoq", "example": "He tried to circumvent the rules."},
        {"word": "clandestine", "translation": "yashirin/maxfiy", "example": "They held a clandestine meeting."},
        {"word": "cogent", "translation": "ishonchli/ta'sirli", "example": "She made a cogent argument."},
        {"word": "cognizant", "translation": "xabardor/anglagan", "example": "Be cognizant of the risks."},
        {"word": "complacent", "translation": "o'z-o'zidan mamnun", "example": "Don't become complacent with success."},
        {"word": "concede", "translation": "tan olmoq/yon bermoq", "example": "He conceded defeat gracefully."},
        {"word": "convoluted", "translation": "murakkab/chigal", "example": "The explanation was too convoluted."},
        {"word": "corroborate", "translation": "tasdiqlash/dalil bilan mustahkamlash", "example": "The witness corroborated the story."},
        {"word": "counterintuitive", "translation": "kutilmagan/aksincha bo'lgan", "example": "The result was counterintuitive."},
        {"word": "credulous", "translation": "soddalib/ishonuvchan", "example": "Don't be too credulous."},
        {"word": "culminate", "translation": "avj olmoq/eng yuqori cho'qqiga chiqmoq", "example": "Years of work culminated in success."},
        {"word": "cynical", "translation": "shubhachi/pessimistik", "example": "He became cynical about politics."},
        {"word": "debilitate", "translation": "zaiflashtirmoq", "example": "The disease debilitated him."},
        {"word": "deferential", "translation": "hurmat ko'rsatuvchi", "example": "She was deferential to her elders."},
        {"word": "deliberate", "translation": "qasddan/ehtiyotkorlik bilan", "example": "It was a deliberate mistake."},
        {"word": "delineate", "translation": "tasvirlamoq/aniqlamoq", "example": "Please delineate the main issues."},
        {"word": "demagogue", "translation": "demagog/ommani boshqaradigan", "example": "Beware of demagogues in politics."},
        {"word": "denigrate", "translation": "mensimaslik/kamsitmoq", "example": "Don't denigrate others' efforts."},
        {"word": "derivative", "translation": "hosilaviy/o'zgalardan olingan", "example": "His style is derivative."},
        {"word": "dichotomy", "translation": "ikkilik/ziddiyat", "example": "There is a clear dichotomy here."},
        {"word": "didactic", "translation": "ta'limiy/nasihatgo'y", "example": "The film has a didactic purpose."},
        {"word": "diffident", "translation": "o'ziga ishonchsiz/tortinchoq", "example": "She seems diffident but is capable."},
        {"word": "discern", "translation": "farqlash/ajratib olmoq", "example": "He can discern truth from lies."},
        {"word": "discordant", "translation": "nomutanosib/uyg'unsiz", "example": "There were discordant opinions."},
        {"word": "disparate", "translation": "farqli/o'zaro bog'liq bo'lmagan", "example": "The two groups had disparate views."},
        {"word": "dissonance", "translation": "kelishmovchilik/uyg'unsizlik", "example": "There was cognitive dissonance."},
        {"word": "dogmatic", "translation": "dogmatik/aqidaparastlik", "example": "Don't be too dogmatic."},
        {"word": "dubious", "translation": "shubhali/gumon", "example": "I am dubious about his claims."},
        {"word": "duplicitous", "translation": "ikki yuzli/aldamchi", "example": "He was duplicitous in negotiations."},
        {"word": "ebullient", "translation": "jo'shqin/hayajonli", "example": "She has an ebullient personality."},
        {"word": "eccentric", "translation": "g'alati/o'ziga xos", "example": "He is an eccentric artist."},
        {"word": "efficacious", "translation": "samarali/natijali", "example": "The treatment proved efficacious."},
        {"word": "egregious", "translation": "juda yomon/sharmandali", "example": "It was an egregious error."},
        {"word": "elusive", "translation": "qo'lga tushmas/noaniq", "example": "The answer remains elusive."},
        {"word": "emulate", "translation": "taqlid qilmoq", "example": "Emulate successful people."},
        {"word": "encapsulate", "translation": "qisqacha ifodalash", "example": "Encapsulate the idea in one sentence."},
        {"word": "endemic", "translation": "tarqalgan/mahalliy", "example": "Poverty is endemic in the region."},
        {"word": "enigmatic", "translation": "sirli/jumboqli", "example": "She smiled in an enigmatic way."},
        {"word": "ephemeral", "translation": "o'tkinchi/qisqa umrli", "example": "Fame is often ephemeral."},
        {"word": "equivocate", "translation": "ikki xil gapirmoq/chalg'itmoq", "example": "Stop equivocating and give a clear answer."},
        {"word": "eradicate", "translation": "yo'q qilmoq/ildizini qirqmoq", "example": "We must eradicate poverty."},
        {"word": "esoteric", "translation": "sir/maxsus bilim talab etuvchi", "example": "The topic is too esoteric."},
        {"word": "exacerbate", "translation": "yomonlashtirmoq/keskinlashtirmoq", "example": "Stress can exacerbate illness."},
        {"word": "exonerate", "translation": "oqlamoq/javobgarlikdan ozod etmoq", "example": "New evidence exonerated him."},
        {"word": "expedient", "translation": "foydali/maqsadga muvofiq", "example": "It was an expedient solution."},
        {"word": "extraneous", "translation": "keraksiz/begona", "example": "Remove extraneous information."},
        {"word": "facetious", "translation": "hazilkash/jiddiy bo'lmagan", "example": "He was being facetious."},
        {"word": "fallacious", "translation": "xato/aldamchi", "example": "This is a fallacious argument."},
        {"word": "fastidious", "translation": "puxta/talabchan", "example": "She is fastidious about cleanliness."},
        {"word": "fatalistic", "translation": "taqdir bilan kelishuvchi", "example": "He has a fatalistic view of life."},
        {"word": "fervent", "translation": "ishtiyoqli/qattiq", "example": "He has a fervent belief."},
        {"word": "flagrant", "translation": "oshkora/ravshanlikda qilingan", "example": "It was a flagrant violation."},
        {"word": "fleeting", "translation": "o'tkinchi/qisqa", "example": "It was a fleeting moment."},
        {"word": "formidable", "translation": "qo'rqinchli/kuchli", "example": "He is a formidable opponent."},
        {"word": "forthright", "translation": "to'g'riso'z/ochiq", "example": "She is forthright in her opinions."},
        {"word": "fractious", "translation": "to'polonchi/asabiy", "example": "The crowd became fractious."},
        {"word": "frivolous", "translation": "bema'ni/jiddiy bo'lmagan", "example": "Don't waste time on frivolous things."},
        {"word": "frugal", "translation": "tejamkor/iqtisodchi", "example": "She lives a frugal life."},
        {"word": "grandiose", "translation": "ulug'vor/o'ta dabdabali", "example": "His grandiose plan failed."},
        {"word": "gregarious", "translation": "ijtimoiy/muloqotsevar", "example": "She is very gregarious."},
        {"word": "hackneyed", "translation": "eskirgan/o'sha-o'sha", "example": "Avoid hackneyed phrases."},
        {"word": "halcyon", "translation": "tinch/osoyishta", "example": "Those were halcyon days."},
        {"word": "hamper", "translation": "to'sqinlik qilmoq", "example": "Bad weather hampered the search."},
        {"word": "harbinger", "translation": "xabarchisi/oldindan belgi", "example": "Dark clouds are a harbinger of rain."},
        {"word": "harrowing", "translation": "dahshatli/ezuvchi", "example": "It was a harrowing experience."},
        {"word": "haughty", "translation": "manmanlik/takabbur", "example": "She had a haughty attitude."},
        {"word": "hegemony", "translation": "hukmronlik/gegemonlik", "example": "The company has market hegemony."},
        {"word": "heretical", "translation": "bid'atchilik/an'anaga zid", "example": "His ideas were considered heretical."},
        {"word": "holistic", "translation": "yaxlit/kompleks", "example": "We need a holistic approach."},
        {"word": "hypocritical", "translation": "munofiqlik/ikki yuzlamachilik", "example": "It is hypocritical to say one thing and do another."},
        {"word": "impartial", "translation": "nохolislik/adolatli", "example": "The judge must be impartial."},
        {"word": "impede", "translation": "to'sqinlik qilmoq", "example": "Bureaucracy impedes progress."},
        {"word": "implicit", "translation": "yashirin/bevosita aytilmagan", "example": "There was implicit criticism."},
        {"word": "impulsive", "translation": "shoshqaloq/o'ylamasdan ish tutuvchi", "example": "Don't make impulsive decisions."},
        {"word": "inadvertent", "translation": "beixtiyor/qasddan emas", "example": "It was an inadvertent mistake."},
        {"word": "incite", "translation": "qo'zg'atmoq/keltirmoq", "example": "Don't incite violence."},
        {"word": "incongruent", "translation": "mos kelmaydigan", "example": "His actions were incongruent with his words."},
        {"word": "indolent", "translation": "dangasa/yalqov", "example": "He became indolent after retiring."},
        {"word": "infer", "translation": "xulosa chiqarmoq", "example": "What can we infer from this?"},
        {"word": "ingenuity", "translation": "zehnavarlik/ijodkorlik", "example": "The solution showed great ingenuity."},
        {"word": "inherent", "translation": "tabiiy/o'ziga xos", "example": "There is an inherent risk."},
        {"word": "innocuous", "translation": "zararsiz/begunoh", "example": "The comment seemed innocuous."},
        {"word": "insidious", "translation": "yashirin zarar beruvchi", "example": "It is an insidious disease."},
        {"word": "intransigent", "translation": "kelishishni istamovchi/qat'iy", "example": "He was intransigent in the debate."},
        {"word": "inundate", "translation": "to'ldirmoq/bosib ketmoq", "example": "We were inundated with requests."},
        {"word": "irrefutable", "translation": "inkor qilib bo'lmaydigan", "example": "The evidence is irrefutable."},
        {"word": "juxtapose", "translation": "yonma-yon qo'ymoq", "example": "Juxtapose the two ideas."},
        {"word": "laconic", "translation": "qisqa va lo'nda", "example": "His reply was laconic."},
        {"word": "lament", "translation": "qayg'urmoq/nola qilmoq", "example": "She lamented the loss."},
        {"word": "latent", "translation": "yashirin/uyqudalik", "example": "The disease was latent for years."},
        {"word": "loquacious", "translation": "ko'p gapiruvchi/sershov", "example": "He is very loquacious."},
        {"word": "lucid", "translation": "aniq/tushunarli", "example": "Please be more lucid."},
        {"word": "magnanimous", "translation": "keng ko'ngilli/saxiy", "example": "He was magnanimous in defeat."},
        {"word": "malevolent", "translation": "yovuz/boshqalarga yomon niyet qiluvchi", "example": "He gave a malevolent look."},
        {"word": "malleable", "translation": "egiluvchan/moslashuvchan", "example": "Young minds are malleable."},
        {"word": "manifest", "translation": "namoyon bo'lmoq/oshkor", "example": "His talent was manifest."},
        {"word": "mendacious", "translation": "yolg'onchi/aldamchi", "example": "The report was mendacious."},
        {"word": "mitigate", "translation": "yumshatmoq/kamaytirmoq", "example": "Mitigate the risks carefully."},
        {"word": "mundane", "translation": "oddiy/kundalik", "example": "He disliked mundane tasks."},
        {"word": "nascent", "translation": "endigina paydo bo'layotgan", "example": "This is a nascent technology."},
        {"word": "nefarious", "translation": "yovuz/jinoyatkorona", "example": "They had nefarious intentions."},
        {"word": "negligible", "translation": "ahamiyatsiz/kichik", "example": "The difference is negligible."},
        {"word": "nuanced", "translation": "nozik/ko'p qirrali", "example": "Her analysis was nuanced."},
        {"word": "obfuscate", "translation": "chalkashtirib yubormoq", "example": "Don't obfuscate the issue."},
        {"word": "obstinate", "translation": "qaysarlik/o'jarlik", "example": "He was obstinate in his refusal."},
        {"word": "obtrusive", "translation": "o'zini ko'p ko'rsatuvchi", "example": "His presence was obtrusive."},
        {"word": "omnipotent", "translation": "qodir/hamma narsani qiloluvchi", "example": "No one is omnipotent."},
        {"word": "onerous", "translation": "og'irlik/yukli", "example": "The task was onerous."},
        {"word": "ostentatious", "translation": "ko'z-ko'z qiluvchi/hashamatli", "example": "His lifestyle was ostentatious."},
        {"word": "overt", "translation": "ochiq/oshkora", "example": "The criticism was overt."},
        {"word": "painstaking", "translation": "g'ayratli/diqqat talab qiluvchi", "example": "She did painstaking research."},
        {"word": "paradox", "translation": "paradoks/ziddiyatli holat", "example": "It is a paradox that war causes peace."},
        {"word": "parsimonious", "translation": "xasis/qo'l yopar", "example": "He is parsimonious with praise."},
        {"word": "pedantic", "translation": "ortiqcha formalist/qoidachilik", "example": "Don't be so pedantic."},
        {"word": "perfidious", "translation": "xiyonatkor/sotqin", "example": "It was a perfidious act."},
        {"word": "peripheral", "translation": "chekkadagi/muhim bo'lmagan", "example": "This is a peripheral issue."},
        {"word": "permeate", "translation": "singib kirmoq/tarqalmoq", "example": "Fear permeated the community."},
        {"word": "pervasive", "translation": "hamma joyda tarqalgan", "example": "Social media is pervasive."},
        {"word": "placate", "translation": "tinchlantirmoq/yumshatmoq", "example": "She tried to placate him."},
        {"word": "platitude", "translation": "ko'p aytilgan gap/klishe", "example": "His speech was full of platitudes."},
        {"word": "plausible", "translation": "mantiqiy/ishonchli", "example": "That seems plausible."},
        {"word": "polarize", "translation": "qutblamoq/ikki tomonga ajratmoq", "example": "The issue polarized the nation."},
        {"word": "pompous", "translation": "o'zini ulug' tutuvchi", "example": "He was pompous in his manner."},
        {"word": "pragmatic", "translation": "amaliy/faollikka asoslangan", "example": "Be pragmatic about the solution."},
        {"word": "precipitate", "translation": "shoshib qilmoq/yog'ingarchilik", "example": "Don't precipitate a crisis."},
        {"word": "precocious", "translation": "erta yetilgan/o'ta zehni o'tkir", "example": "She was a precocious child."},
        {"word": "prescient", "translation": "oldindan biluvchi", "example": "His prediction was prescient."},
        {"word": "presumptuous", "translation": "o'zini suquvchi/betakalluf", "example": "It was presumptuous of him."},
        {"word": "prevalent", "translation": "keng tarqalgan", "example": "Smartphones are prevalent today."},
        {"word": "procrastinate", "translation": "kechiktirmoq/cho'zmoq", "example": "Stop procrastinating."},
        {"word": "profound", "translation": "chuqur/jiddiy", "example": "He made a profound observation."},
        {"word": "proliferate", "translation": "ko'paymoq/tarqalmoq", "example": "Social media apps proliferate quickly."},
        {"word": "propitious", "translation": "qulay/omadli", "example": "The weather was propitious."},
        {"word": "prosaic", "translation": "oddiy/zerikarli", "example": "Life can be prosaic sometimes."},
        {"word": "provocative", "translation": "qo'zg'atuvchi/provokatsion", "example": "The statement was provocative."},
        {"word": "prudent", "translation": "ehtiyotkor/donolik bilan ish tutuvchi", "example": "It is prudent to save money."},
        {"word": "punctilious", "translation": "qoida va tartibga qat'iy rioya qiluvchi", "example": "She is punctilious about manners."},
        {"word": "querulous", "translation": "nolakash/doim shikoyat qiluvchi", "example": "He became querulous in old age."},
        {"word": "quintessential", "translation": "eng tipik/o'ziga xos", "example": "She is the quintessential leader."},
        {"word": "ramification", "translation": "oqibat/tarmoqlanish", "example": "Consider the ramifications."},
        {"word": "recalcitrant", "translation": "itoat etmaydigan/o'jar", "example": "The student was recalcitrant."},
        {"word": "reconcile", "translation": "yarashmoq/muvofiqlashtirmoq", "example": "Reconcile your differences."},
        {"word": "redundant", "translation": "ortiqcha/keraksiz", "example": "Remove redundant words."},
        {"word": "refractory", "translation": "boshqarib bo'lmaydigan/o'tar", "example": "The patient was refractory to treatment."},
        {"word": "relentless", "translation": "to'xtovsiz/qaysarlik bilan davom etuvchi", "example": "He was relentless in pursuit."},
        {"word": "reminisce", "translation": "xotiralamoq/eslamoq", "example": "She liked to reminisce."},
        {"word": "reprehensible", "translation": "koyishga loyiq/qoralanuvchi", "example": "His behaviour was reprehensible."},
        {"word": "resilient", "translation": "bardoshli/qayta tiklanuvchi", "example": "Be resilient in hard times."},
        {"word": "resolute", "translation": "qat'iyatli/mustahkam", "example": "She was resolute in her decision."},
        {"word": "reticent", "translation": "gapirmaydigan/ziqna", "example": "He was reticent about his past."},
        {"word": "rhetoric", "translation": "ritorika/nutq san'ati", "example": "His rhetoric was persuasive."},
        {"word": "rigorous", "translation": "qat'iy/talabchan", "example": "Apply rigorous standards."},
        {"word": "rudimentary", "translation": "boshlang'ich/asosiy", "example": "He has rudimentary knowledge."},
        {"word": "sagacious", "translation": "dono/o'tkir zehinli", "example": "She is a sagacious leader."},
        {"word": "sanctimonious", "translation": "taqvodorlikni ko'rsatuvchi/riyokor", "example": "His tone was sanctimonious."},
        {"word": "sardonic", "translation": "masxaraomuz/kinoyali", "example": "He had a sardonic smile."},
        {"word": "sceptical", "translation": "shubhachi/ishonchsiz", "example": "I am sceptical about this claim."},
        {"word": "sedulous", "translation": "g'ayratli/tirishqoq", "example": "She was sedulous in her work."},
        {"word": "serendipity", "translation": "baxtli tasodif", "example": "Meeting her was pure serendipity."},
        {"word": "solicitous", "translation": "g'amxo'r/tashvishlanuvchi", "example": "She was solicitous for his wellbeing."},
        {"word": "soporific", "translation": "uyqu keltiruvchi/zerikarli", "example": "The lecture was soporific."},
        {"word": "specious", "translation": "sirtdan to'g'ri ko'rinadigan lekin xato", "example": "His argument was specious."},
        {"word": "sporadic", "translation": "vaqti-vaqti bilan/tartibsiz", "example": "Rain was sporadic today."},
        {"word": "spurious", "translation": "soxta/nohaqiqiy", "example": "He made spurious claims."},
        {"word": "steadfast", "translation": "qat'iyatli/sodiq", "example": "She remained steadfast."},
        {"word": "stoic", "translation": "o'zini tutib, iztirob sezmovchi", "example": "He faced loss with stoic calm."},
        {"word": "subversive", "translation": "tuzumni ag'daruvchi", "example": "The group had subversive intentions."},
        {"word": "succinct", "translation": "qisqa va aniq", "example": "Give a succinct answer."},
        {"word": "superfluous", "translation": "ortiqcha/kerak bo'lmagan", "example": "Remove all superfluous detail."},
        {"word": "sycophantic", "translation": "xushomadgo'y/yaltoqi", "example": "He was surrounded by sycophantic followers."},
        {"word": "taciturn", "translation": "kamgap/sergak", "example": "He was taciturn at meetings."},
        {"word": "tangential", "translation": "mavzudan chetlashuvchi", "example": "Your point is tangential."},
        {"word": "tenacious", "translation": "qat'iyatli/tirishqoq", "example": "Be tenacious and keep trying."},
        {"word": "terse", "translation": "qisqa/quruq", "example": "His reply was terse."},
        {"word": "timorous", "translation": "qo'rqoq/tortinchoq", "example": "She was timorous by nature."},
        {"word": "torpor", "translation": "beparvolik/hushyorsizlik", "example": "He fell into a state of torpor."},
        {"word": "transient", "translation": "o'tkinchi/vaqtinchalik", "example": "Fame is transient."},
        {"word": "trepidation", "translation": "qo'rquv/xavotir", "example": "She spoke with trepidation."},
        {"word": "truculent", "translation": "jangari/begona narsaga dushmanlik", "example": "He was truculent in the debate."},
        {"word": "turbulent", "translation": "notinch/bo'ronli", "example": "It was a turbulent period."},
        {"word": "ubiquitous", "translation": "hamma joyda bor", "example": "Smartphones are ubiquitous now."},
        {"word": "unassailable", "translation": "hech kim inkor qila olmaydigan", "example": "Her logic was unassailable."},
        {"word": "unequivocal", "translation": "aniq/shubhasiz", "example": "Give an unequivocal answer."},
        {"word": "vacillate", "translation": "tebranmoq/ikkilanmoq", "example": "He vacillated between two choices."},
        {"word": "vapid", "translation": "zerikarli/mazmunsiz", "example": "The speech was vapid."},
        {"word": "venerate", "translation": "hurmat qilmoq/ulug'lamoq", "example": "We venerate our ancestors."},
        {"word": "verbose", "translation": "ko'p so'zli/uzun-u-quruq", "example": "Try not to be verbose."},
        {"word": "vicarious", "translation": "boshqa orqali his etish", "example": "I felt vicarious pleasure."},
        {"word": "vindicate", "translation": "oqlamoq/to'g'riligini isbotlamoq", "example": "New facts vindicated him."},
        {"word": "vitriolic", "translation": "o'tkir/o'yuvchi (gapda)", "example": "The critic gave a vitriolic review."},
        {"word": "vociferous", "translation": "shovqinli/baland ovozda e'tiroz bildiruvchi", "example": "There was vociferous opposition."},
        {"word": "volatile", "translation": "o'zgaruvchan/beqaror", "example": "The market is volatile."},
        {"word": "whimsical", "translation": "kayfiyatga qarab/bema'ni", "example": "She had a whimsical sense of humor."},
        {"word": "zealous", "translation": "ishtiyoqli/g'ayratli", "example": "He was zealous in his work."},
    ]
}    
